services:
  - type: web
    name: student-management-system
    env: java
    plan: free
    buildCommand: mvn clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
